on:
  push:
    branches:
      - main

jobs:
  deploy-main:
    runs-on: codeberg-tiny

    steps:
      - name: Deploy main
        uses: latzo/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            deploy-main
