on:
  push:
    branches:
      - main

jobs:
  deploy-main:
    runs-on: debian-latest

    steps:
      - name: Deploy main
        uses: latzo/ssh-action
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            deploy-main
